/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.jarviscrawlercore.AliProduct', null, global);
goog.exportSymbol('proto.jarviscrawlercore.AlimamaMode', null, global);
goog.exportSymbol('proto.jarviscrawlercore.AlimamaProduct', null, global);
goog.exportSymbol('proto.jarviscrawlercore.AlimamaProducts', null, global);
goog.exportSymbol('proto.jarviscrawlercore.AlimamaTopInfo', null, global);
goog.exportSymbol('proto.jarviscrawlercore.AlimamaTopProducts', null, global);
goog.exportSymbol('proto.jarviscrawlercore.ReplyAlimama', null, global);
goog.exportSymbol('proto.jarviscrawlercore.RequestAlimama', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.AlimamaProduct = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.AlimamaProduct.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.AlimamaProduct, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.AlimamaProduct.displayName = 'proto.jarviscrawlercore.AlimamaProduct';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.AlimamaProduct.repeatedFields_ = [10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.AlimamaProduct.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.AlimamaProduct} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.AlimamaProduct.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    url: jspb.Message.getFieldWithDefault(msg, 2, ""),
    shop: jspb.Message.getFieldWithDefault(msg, 3, ""),
    img: jspb.Message.getFieldWithDefault(msg, 4, ""),
    lastcoupon: +jspb.Message.getFieldWithDefault(msg, 5, 0.0),
    curprice: +jspb.Message.getFieldWithDefault(msg, 6, 0.0),
    rebate: +jspb.Message.getFieldWithDefault(msg, 7, 0.0),
    commission: +jspb.Message.getFieldWithDefault(msg, 8, 0.0),
    moneyquan: +jspb.Message.getFieldWithDefault(msg, 9, 0.0),
    shoptypeList: jspb.Message.getRepeatedField(msg, 10),
    salesvolume: jspb.Message.getFieldWithDefault(msg, 11, 0),
    shopurl: jspb.Message.getFieldWithDefault(msg, 12, ""),
    salesvolume2: jspb.Message.getFieldWithDefault(msg, 13, 0),
    presale: +jspb.Message.getFieldWithDefault(msg, 14, 0.0),
    presaleprofit: +jspb.Message.getFieldWithDefault(msg, 15, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.AlimamaProduct}
 */
proto.jarviscrawlercore.AlimamaProduct.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.AlimamaProduct;
  return proto.jarviscrawlercore.AlimamaProduct.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.AlimamaProduct} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.AlimamaProduct}
 */
proto.jarviscrawlercore.AlimamaProduct.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setShop(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setImg(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLastcoupon(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setCurprice(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRebate(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setCommission(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMoneyquan(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addShoptype(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSalesvolume(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setShopurl(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSalesvolume2(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPresale(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPresaleprofit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.AlimamaProduct.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.AlimamaProduct} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.AlimamaProduct.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getShop();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getImg();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLastcoupon();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getCurprice();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getRebate();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getCommission();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getMoneyquan();
  if (f !== 0.0) {
    writer.writeFloat(
      9,
      f
    );
  }
  f = message.getShoptypeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getSalesvolume();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getShopurl();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getSalesvolume2();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getPresale();
  if (f !== 0.0) {
    writer.writeFloat(
      14,
      f
    );
  }
  f = message.getPresaleprofit();
  if (f !== 0.0) {
    writer.writeFloat(
      15,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string url = 2;
 * @return {string}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setUrl = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string shop = 3;
 * @return {string}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getShop = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setShop = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string img = 4;
 * @return {string}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getImg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setImg = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional float lastCoupon = 5;
 * @return {number}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getLastcoupon = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setLastcoupon = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float curPrice = 6;
 * @return {number}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getCurprice = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 6, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setCurprice = function(value) {
  jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional float rebate = 7;
 * @return {number}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getRebate = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 7, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setRebate = function(value) {
  jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional float commission = 8;
 * @return {number}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getCommission = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 8, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setCommission = function(value) {
  jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional float moneyQuan = 9;
 * @return {number}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getMoneyquan = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 9, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setMoneyquan = function(value) {
  jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * repeated string shopType = 10;
 * @return {!Array<string>}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getShoptypeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/** @param {!Array<string>} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setShoptypeList = function(value) {
  jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.addShoptype = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


proto.jarviscrawlercore.AlimamaProduct.prototype.clearShoptypeList = function() {
  this.setShoptypeList([]);
};


/**
 * optional int32 salesVolume = 11;
 * @return {number}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getSalesvolume = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setSalesvolume = function(value) {
  jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional string shopurl = 12;
 * @return {string}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getShopurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setShopurl = function(value) {
  jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional int32 salesVolume2 = 13;
 * @return {number}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getSalesvolume2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setSalesvolume2 = function(value) {
  jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional float presale = 14;
 * @return {number}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getPresale = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 14, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setPresale = function(value) {
  jspb.Message.setProto3FloatField(this, 14, value);
};


/**
 * optional float presaleProfit = 15;
 * @return {number}
 */
proto.jarviscrawlercore.AlimamaProduct.prototype.getPresaleprofit = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 15, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.AlimamaProduct.prototype.setPresaleprofit = function(value) {
  jspb.Message.setProto3FloatField(this, 15, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.AliProduct = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.AliProduct.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.AliProduct, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.AliProduct.displayName = 'proto.jarviscrawlercore.AliProduct';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.AliProduct.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.AliProduct.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.AliProduct.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.AliProduct} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.AliProduct.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    product: (f = msg.getProduct()) && proto.jarviscrawlercore.AlimamaProduct.toObject(includeInstance, f),
    tagsList: jspb.Message.getRepeatedField(msg, 3),
    img: jspb.Message.getFieldWithDefault(msg, 4, ""),
    ranktimes: jspb.Message.getFieldWithDefault(msg, 5, 0),
    ranktimes2: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.AliProduct}
 */
proto.jarviscrawlercore.AliProduct.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.AliProduct;
  return proto.jarviscrawlercore.AliProduct.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.AliProduct} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.AliProduct}
 */
proto.jarviscrawlercore.AliProduct.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.jarviscrawlercore.AlimamaProduct;
      reader.readMessage(value,proto.jarviscrawlercore.AlimamaProduct.deserializeBinaryFromReader);
      msg.setProduct(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addTags(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setImg(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRanktimes(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRanktimes2(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.AliProduct.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.AliProduct.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.AliProduct} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.AliProduct.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProduct();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.jarviscrawlercore.AlimamaProduct.serializeBinaryToWriter
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getImg();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRanktimes();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getRanktimes2();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
};


/**
 * optional string ID = 1;
 * @return {string}
 */
proto.jarviscrawlercore.AliProduct.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.AliProduct.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional AlimamaProduct product = 2;
 * @return {?proto.jarviscrawlercore.AlimamaProduct}
 */
proto.jarviscrawlercore.AliProduct.prototype.getProduct = function() {
  return /** @type{?proto.jarviscrawlercore.AlimamaProduct} */ (
    jspb.Message.getWrapperField(this, proto.jarviscrawlercore.AlimamaProduct, 2));
};


/** @param {?proto.jarviscrawlercore.AlimamaProduct|undefined} value */
proto.jarviscrawlercore.AliProduct.prototype.setProduct = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.jarviscrawlercore.AliProduct.prototype.clearProduct = function() {
  this.setProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jarviscrawlercore.AliProduct.prototype.hasProduct = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated string tags = 3;
 * @return {!Array<string>}
 */
proto.jarviscrawlercore.AliProduct.prototype.getTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<string>} value */
proto.jarviscrawlercore.AliProduct.prototype.setTagsList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.jarviscrawlercore.AliProduct.prototype.addTags = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.jarviscrawlercore.AliProduct.prototype.clearTagsList = function() {
  this.setTagsList([]);
};


/**
 * optional string img = 4;
 * @return {string}
 */
proto.jarviscrawlercore.AliProduct.prototype.getImg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.AliProduct.prototype.setImg = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 rankTimes = 5;
 * @return {number}
 */
proto.jarviscrawlercore.AliProduct.prototype.getRanktimes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.AliProduct.prototype.setRanktimes = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 rankTimes2 = 6;
 * @return {number}
 */
proto.jarviscrawlercore.AliProduct.prototype.getRanktimes2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.AliProduct.prototype.setRanktimes2 = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.AlimamaTopProducts = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.AlimamaTopProducts.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.AlimamaTopProducts, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.AlimamaTopProducts.displayName = 'proto.jarviscrawlercore.AlimamaTopProducts';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.AlimamaTopProducts.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.AlimamaTopProducts.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.AlimamaTopProducts.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.AlimamaTopProducts} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.AlimamaTopProducts.toObject = function(includeInstance, msg) {
  var f, obj = {
    categoryList: jspb.Message.getRepeatedField(msg, 1),
    productsList: jspb.Message.toObjectList(msg.getProductsList(),
    proto.jarviscrawlercore.AlimamaProduct.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.AlimamaTopProducts}
 */
proto.jarviscrawlercore.AlimamaTopProducts.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.AlimamaTopProducts;
  return proto.jarviscrawlercore.AlimamaTopProducts.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.AlimamaTopProducts} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.AlimamaTopProducts}
 */
proto.jarviscrawlercore.AlimamaTopProducts.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addCategory(value);
      break;
    case 2:
      var value = new proto.jarviscrawlercore.AlimamaProduct;
      reader.readMessage(value,proto.jarviscrawlercore.AlimamaProduct.deserializeBinaryFromReader);
      msg.addProducts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.AlimamaTopProducts.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.AlimamaTopProducts.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.AlimamaTopProducts} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.AlimamaTopProducts.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCategoryList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getProductsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.jarviscrawlercore.AlimamaProduct.serializeBinaryToWriter
    );
  }
};


/**
 * repeated string category = 1;
 * @return {!Array<string>}
 */
proto.jarviscrawlercore.AlimamaTopProducts.prototype.getCategoryList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.jarviscrawlercore.AlimamaTopProducts.prototype.setCategoryList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.jarviscrawlercore.AlimamaTopProducts.prototype.addCategory = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.jarviscrawlercore.AlimamaTopProducts.prototype.clearCategoryList = function() {
  this.setCategoryList([]);
};


/**
 * repeated AlimamaProduct products = 2;
 * @return {!Array<!proto.jarviscrawlercore.AlimamaProduct>}
 */
proto.jarviscrawlercore.AlimamaTopProducts.prototype.getProductsList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.AlimamaProduct>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.AlimamaProduct, 2));
};


/** @param {!Array<!proto.jarviscrawlercore.AlimamaProduct>} value */
proto.jarviscrawlercore.AlimamaTopProducts.prototype.setProductsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.jarviscrawlercore.AlimamaProduct=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.AlimamaProduct}
 */
proto.jarviscrawlercore.AlimamaTopProducts.prototype.addProducts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.jarviscrawlercore.AlimamaProduct, opt_index);
};


proto.jarviscrawlercore.AlimamaTopProducts.prototype.clearProductsList = function() {
  this.setProductsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.AlimamaTopInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.AlimamaTopInfo.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.AlimamaTopInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.AlimamaTopInfo.displayName = 'proto.jarviscrawlercore.AlimamaTopInfo';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.AlimamaTopInfo.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.AlimamaTopInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.AlimamaTopInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.AlimamaTopInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.AlimamaTopInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    lstList: jspb.Message.toObjectList(msg.getLstList(),
    proto.jarviscrawlercore.AlimamaTopProducts.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.AlimamaTopInfo}
 */
proto.jarviscrawlercore.AlimamaTopInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.AlimamaTopInfo;
  return proto.jarviscrawlercore.AlimamaTopInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.AlimamaTopInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.AlimamaTopInfo}
 */
proto.jarviscrawlercore.AlimamaTopInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.jarviscrawlercore.AlimamaTopProducts;
      reader.readMessage(value,proto.jarviscrawlercore.AlimamaTopProducts.deserializeBinaryFromReader);
      msg.addLst(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.AlimamaTopInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.AlimamaTopInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.AlimamaTopInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.AlimamaTopInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLstList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.jarviscrawlercore.AlimamaTopProducts.serializeBinaryToWriter
    );
  }
};


/**
 * repeated AlimamaTopProducts lst = 1;
 * @return {!Array<!proto.jarviscrawlercore.AlimamaTopProducts>}
 */
proto.jarviscrawlercore.AlimamaTopInfo.prototype.getLstList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.AlimamaTopProducts>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.AlimamaTopProducts, 1));
};


/** @param {!Array<!proto.jarviscrawlercore.AlimamaTopProducts>} value */
proto.jarviscrawlercore.AlimamaTopInfo.prototype.setLstList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.jarviscrawlercore.AlimamaTopProducts=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.AlimamaTopProducts}
 */
proto.jarviscrawlercore.AlimamaTopInfo.prototype.addLst = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.jarviscrawlercore.AlimamaTopProducts, opt_index);
};


proto.jarviscrawlercore.AlimamaTopInfo.prototype.clearLstList = function() {
  this.setLstList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.AlimamaProducts = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.AlimamaProducts.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.AlimamaProducts, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.AlimamaProducts.displayName = 'proto.jarviscrawlercore.AlimamaProducts';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.AlimamaProducts.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.AlimamaProducts.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.AlimamaProducts.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.AlimamaProducts} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.AlimamaProducts.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, ""),
    productsList: jspb.Message.toObjectList(msg.getProductsList(),
    proto.jarviscrawlercore.AlimamaProduct.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.AlimamaProducts}
 */
proto.jarviscrawlercore.AlimamaProducts.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.AlimamaProducts;
  return proto.jarviscrawlercore.AlimamaProducts.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.AlimamaProducts} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.AlimamaProducts}
 */
proto.jarviscrawlercore.AlimamaProducts.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 2:
      var value = new proto.jarviscrawlercore.AlimamaProduct;
      reader.readMessage(value,proto.jarviscrawlercore.AlimamaProduct.deserializeBinaryFromReader);
      msg.addProducts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.AlimamaProducts.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.AlimamaProducts.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.AlimamaProducts} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.AlimamaProducts.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProductsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.jarviscrawlercore.AlimamaProduct.serializeBinaryToWriter
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.jarviscrawlercore.AlimamaProducts.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.AlimamaProducts.prototype.setText = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated AlimamaProduct products = 2;
 * @return {!Array<!proto.jarviscrawlercore.AlimamaProduct>}
 */
proto.jarviscrawlercore.AlimamaProducts.prototype.getProductsList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.AlimamaProduct>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.AlimamaProduct, 2));
};


/** @param {!Array<!proto.jarviscrawlercore.AlimamaProduct>} value */
proto.jarviscrawlercore.AlimamaProducts.prototype.setProductsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.jarviscrawlercore.AlimamaProduct=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.AlimamaProduct}
 */
proto.jarviscrawlercore.AlimamaProducts.prototype.addProducts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.jarviscrawlercore.AlimamaProduct, opt_index);
};


proto.jarviscrawlercore.AlimamaProducts.prototype.clearProductsList = function() {
  this.setProductsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.RequestAlimama = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jarviscrawlercore.RequestAlimama, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.RequestAlimama.displayName = 'proto.jarviscrawlercore.RequestAlimama';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.RequestAlimama.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.RequestAlimama.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.RequestAlimama} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.RequestAlimama.toObject = function(includeInstance, msg) {
  var f, obj = {
    mode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    text: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.RequestAlimama}
 */
proto.jarviscrawlercore.RequestAlimama.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.RequestAlimama;
  return proto.jarviscrawlercore.RequestAlimama.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.RequestAlimama} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.RequestAlimama}
 */
proto.jarviscrawlercore.RequestAlimama.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.jarviscrawlercore.AlimamaMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.RequestAlimama.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.RequestAlimama.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.RequestAlimama} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.RequestAlimama.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional AlimamaMode mode = 1;
 * @return {!proto.jarviscrawlercore.AlimamaMode}
 */
proto.jarviscrawlercore.RequestAlimama.prototype.getMode = function() {
  return /** @type {!proto.jarviscrawlercore.AlimamaMode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.jarviscrawlercore.AlimamaMode} value */
proto.jarviscrawlercore.RequestAlimama.prototype.setMode = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string text = 2;
 * @return {string}
 */
proto.jarviscrawlercore.RequestAlimama.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.RequestAlimama.prototype.setText = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.ReplyAlimama = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.jarviscrawlercore.ReplyAlimama.oneofGroups_);
};
goog.inherits(proto.jarviscrawlercore.ReplyAlimama, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.ReplyAlimama.displayName = 'proto.jarviscrawlercore.ReplyAlimama';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.jarviscrawlercore.ReplyAlimama.oneofGroups_ = [[100,101]];

/**
 * @enum {number}
 */
proto.jarviscrawlercore.ReplyAlimama.ReplyCase = {
  REPLY_NOT_SET: 0,
  PRODUCTS: 100,
  TOPINFO: 101
};

/**
 * @return {proto.jarviscrawlercore.ReplyAlimama.ReplyCase}
 */
proto.jarviscrawlercore.ReplyAlimama.prototype.getReplyCase = function() {
  return /** @type {proto.jarviscrawlercore.ReplyAlimama.ReplyCase} */(jspb.Message.computeOneofCase(this, proto.jarviscrawlercore.ReplyAlimama.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.ReplyAlimama.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.ReplyAlimama.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.ReplyAlimama} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ReplyAlimama.toObject = function(includeInstance, msg) {
  var f, obj = {
    mode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    products: (f = msg.getProducts()) && proto.jarviscrawlercore.AlimamaProducts.toObject(includeInstance, f),
    topinfo: (f = msg.getTopinfo()) && proto.jarviscrawlercore.AlimamaTopInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.ReplyAlimama}
 */
proto.jarviscrawlercore.ReplyAlimama.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.ReplyAlimama;
  return proto.jarviscrawlercore.ReplyAlimama.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.ReplyAlimama} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.ReplyAlimama}
 */
proto.jarviscrawlercore.ReplyAlimama.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.jarviscrawlercore.AlimamaMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    case 100:
      var value = new proto.jarviscrawlercore.AlimamaProducts;
      reader.readMessage(value,proto.jarviscrawlercore.AlimamaProducts.deserializeBinaryFromReader);
      msg.setProducts(value);
      break;
    case 101:
      var value = new proto.jarviscrawlercore.AlimamaTopInfo;
      reader.readMessage(value,proto.jarviscrawlercore.AlimamaTopInfo.deserializeBinaryFromReader);
      msg.setTopinfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.ReplyAlimama.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.ReplyAlimama.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.ReplyAlimama} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ReplyAlimama.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getProducts();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.jarviscrawlercore.AlimamaProducts.serializeBinaryToWriter
    );
  }
  f = message.getTopinfo();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      proto.jarviscrawlercore.AlimamaTopInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional AlimamaMode mode = 1;
 * @return {!proto.jarviscrawlercore.AlimamaMode}
 */
proto.jarviscrawlercore.ReplyAlimama.prototype.getMode = function() {
  return /** @type {!proto.jarviscrawlercore.AlimamaMode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.jarviscrawlercore.AlimamaMode} value */
proto.jarviscrawlercore.ReplyAlimama.prototype.setMode = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional AlimamaProducts products = 100;
 * @return {?proto.jarviscrawlercore.AlimamaProducts}
 */
proto.jarviscrawlercore.ReplyAlimama.prototype.getProducts = function() {
  return /** @type{?proto.jarviscrawlercore.AlimamaProducts} */ (
    jspb.Message.getWrapperField(this, proto.jarviscrawlercore.AlimamaProducts, 100));
};


/** @param {?proto.jarviscrawlercore.AlimamaProducts|undefined} value */
proto.jarviscrawlercore.ReplyAlimama.prototype.setProducts = function(value) {
  jspb.Message.setOneofWrapperField(this, 100, proto.jarviscrawlercore.ReplyAlimama.oneofGroups_[0], value);
};


proto.jarviscrawlercore.ReplyAlimama.prototype.clearProducts = function() {
  this.setProducts(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jarviscrawlercore.ReplyAlimama.prototype.hasProducts = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional AlimamaTopInfo topInfo = 101;
 * @return {?proto.jarviscrawlercore.AlimamaTopInfo}
 */
proto.jarviscrawlercore.ReplyAlimama.prototype.getTopinfo = function() {
  return /** @type{?proto.jarviscrawlercore.AlimamaTopInfo} */ (
    jspb.Message.getWrapperField(this, proto.jarviscrawlercore.AlimamaTopInfo, 101));
};


/** @param {?proto.jarviscrawlercore.AlimamaTopInfo|undefined} value */
proto.jarviscrawlercore.ReplyAlimama.prototype.setTopinfo = function(value) {
  jspb.Message.setOneofWrapperField(this, 101, proto.jarviscrawlercore.ReplyAlimama.oneofGroups_[0], value);
};


proto.jarviscrawlercore.ReplyAlimama.prototype.clearTopinfo = function() {
  this.setTopinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jarviscrawlercore.ReplyAlimama.prototype.hasTopinfo = function() {
  return jspb.Message.getField(this, 101) != null;
};


/**
 * @enum {number}
 */
proto.jarviscrawlercore.AlimamaMode = {
  ALIMMM_KEEPALIVE: 0,
  ALIMMM_SEARCH: 1,
  ALIMMM_GETTOP: 2
};

goog.object.extend(exports, proto.jarviscrawlercore);
