/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.jarviscrawlercore.ReplyTmall', null, global);
goog.exportSymbol('proto.jarviscrawlercore.RequestTmall', null, global);
goog.exportSymbol('proto.jarviscrawlercore.TmallMode', null, global);
goog.exportSymbol('proto.jarviscrawlercore.TmallProduct', null, global);
goog.exportSymbol('proto.jarviscrawlercore.TmallProductHistory', null, global);
goog.exportSymbol('proto.jarviscrawlercore.TmallProperty', null, global);
goog.exportSymbol('proto.jarviscrawlercore.TmallReviewTag', null, global);
goog.exportSymbol('proto.jarviscrawlercore.TmallSKUInfo', null, global);
goog.exportSymbol('proto.jarviscrawlercore.TmallShopInfo', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.TmallSKUInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jarviscrawlercore.TmallSKUInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.TmallSKUInfo.displayName = 'proto.jarviscrawlercore.TmallSKUInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.TmallSKUInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.TmallSKUInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.TmallSKUInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallSKUInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    skuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    price: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    title: jspb.Message.getFieldWithDefault(msg, 3, ""),
    img: jspb.Message.getFieldWithDefault(msg, 4, ""),
    stock: jspb.Message.getFieldWithDefault(msg, 5, 0),
    originalprice: +jspb.Message.getFieldWithDefault(msg, 6, 0.0),
    wl: jspb.Message.getFieldWithDefault(msg, 7, ""),
    wlprice: +jspb.Message.getFieldWithDefault(msg, 8, 0.0),
    wlstr: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.TmallSKUInfo}
 */
proto.jarviscrawlercore.TmallSKUInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.TmallSKUInfo;
  return proto.jarviscrawlercore.TmallSKUInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.TmallSKUInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.TmallSKUInfo}
 */
proto.jarviscrawlercore.TmallSKUInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSkuid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPrice(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setImg(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStock(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setOriginalprice(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setWl(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setWlprice(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setWlstr(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.TmallSKUInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.TmallSKUInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.TmallSKUInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallSKUInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSkuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getImg();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStock();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getOriginalprice();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getWl();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getWlprice();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getWlstr();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional string skuid = 1;
 * @return {string}
 */
proto.jarviscrawlercore.TmallSKUInfo.prototype.getSkuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallSKUInfo.prototype.setSkuid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float price = 2;
 * @return {number}
 */
proto.jarviscrawlercore.TmallSKUInfo.prototype.getPrice = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallSKUInfo.prototype.setPrice = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional string title = 3;
 * @return {string}
 */
proto.jarviscrawlercore.TmallSKUInfo.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallSKUInfo.prototype.setTitle = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string img = 4;
 * @return {string}
 */
proto.jarviscrawlercore.TmallSKUInfo.prototype.getImg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallSKUInfo.prototype.setImg = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 stock = 5;
 * @return {number}
 */
proto.jarviscrawlercore.TmallSKUInfo.prototype.getStock = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallSKUInfo.prototype.setStock = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional float originalPrice = 6;
 * @return {number}
 */
proto.jarviscrawlercore.TmallSKUInfo.prototype.getOriginalprice = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 6, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallSKUInfo.prototype.setOriginalprice = function(value) {
  jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional string wl = 7;
 * @return {string}
 */
proto.jarviscrawlercore.TmallSKUInfo.prototype.getWl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallSKUInfo.prototype.setWl = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional float wlPrice = 8;
 * @return {number}
 */
proto.jarviscrawlercore.TmallSKUInfo.prototype.getWlprice = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 8, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallSKUInfo.prototype.setWlprice = function(value) {
  jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional string wlStr = 9;
 * @return {string}
 */
proto.jarviscrawlercore.TmallSKUInfo.prototype.getWlstr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallSKUInfo.prototype.setWlstr = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.TmallProductHistory = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.TmallProductHistory.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.TmallProductHistory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.TmallProductHistory.displayName = 'proto.jarviscrawlercore.TmallProductHistory';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.TmallProductHistory.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.TmallProductHistory.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.TmallProductHistory.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.TmallProductHistory} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallProductHistory.toObject = function(includeInstance, msg) {
  var f, obj = {
    skusList: jspb.Message.toObjectList(msg.getSkusList(),
    proto.jarviscrawlercore.TmallSKUInfo.toObject, includeInstance),
    lastupdatedtime: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.TmallProductHistory}
 */
proto.jarviscrawlercore.TmallProductHistory.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.TmallProductHistory;
  return proto.jarviscrawlercore.TmallProductHistory.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.TmallProductHistory} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.TmallProductHistory}
 */
proto.jarviscrawlercore.TmallProductHistory.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.jarviscrawlercore.TmallSKUInfo;
      reader.readMessage(value,proto.jarviscrawlercore.TmallSKUInfo.deserializeBinaryFromReader);
      msg.addSkus(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastupdatedtime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.TmallProductHistory.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.TmallProductHistory.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.TmallProductHistory} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallProductHistory.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSkusList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.jarviscrawlercore.TmallSKUInfo.serializeBinaryToWriter
    );
  }
  f = message.getLastupdatedtime();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * repeated TmallSKUInfo skus = 1;
 * @return {!Array<!proto.jarviscrawlercore.TmallSKUInfo>}
 */
proto.jarviscrawlercore.TmallProductHistory.prototype.getSkusList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.TmallSKUInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.TmallSKUInfo, 1));
};


/** @param {!Array<!proto.jarviscrawlercore.TmallSKUInfo>} value */
proto.jarviscrawlercore.TmallProductHistory.prototype.setSkusList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.jarviscrawlercore.TmallSKUInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.TmallSKUInfo}
 */
proto.jarviscrawlercore.TmallProductHistory.prototype.addSkus = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.jarviscrawlercore.TmallSKUInfo, opt_index);
};


proto.jarviscrawlercore.TmallProductHistory.prototype.clearSkusList = function() {
  this.setSkusList([]);
};


/**
 * optional int64 lastUpdatedTime = 2;
 * @return {number}
 */
proto.jarviscrawlercore.TmallProductHistory.prototype.getLastupdatedtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallProductHistory.prototype.setLastupdatedtime = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.TmallReviewTag = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jarviscrawlercore.TmallReviewTag, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.TmallReviewTag.displayName = 'proto.jarviscrawlercore.TmallReviewTag';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.TmallReviewTag.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.TmallReviewTag.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.TmallReviewTag} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallReviewTag.toObject = function(includeInstance, msg) {
  var f, obj = {
    tag: jspb.Message.getFieldWithDefault(msg, 1, ""),
    times: jspb.Message.getFieldWithDefault(msg, 2, 0),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.TmallReviewTag}
 */
proto.jarviscrawlercore.TmallReviewTag.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.TmallReviewTag;
  return proto.jarviscrawlercore.TmallReviewTag.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.TmallReviewTag} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.TmallReviewTag}
 */
proto.jarviscrawlercore.TmallReviewTag.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimes(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.TmallReviewTag.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.TmallReviewTag.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.TmallReviewTag} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallReviewTag.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimes();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getType();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string tag = 1;
 * @return {string}
 */
proto.jarviscrawlercore.TmallReviewTag.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallReviewTag.prototype.setTag = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 times = 2;
 * @return {number}
 */
proto.jarviscrawlercore.TmallReviewTag.prototype.getTimes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallReviewTag.prototype.setTimes = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 type = 3;
 * @return {number}
 */
proto.jarviscrawlercore.TmallReviewTag.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallReviewTag.prototype.setType = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.TmallShopInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.TmallShopInfo.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.TmallShopInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.TmallShopInfo.displayName = 'proto.jarviscrawlercore.TmallShopInfo';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.TmallShopInfo.repeatedFields_ = [6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.TmallShopInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.TmallShopInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallShopInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    gold: jspb.Message.getFieldWithDefault(msg, 2, false),
    url: jspb.Message.getFieldWithDefault(msg, 3, ""),
    rank: jspb.Message.getFieldWithDefault(msg, 4, ""),
    rating: jspb.Message.getFieldWithDefault(msg, 5, 0),
    ratelevelList: jspb.Message.getRepeatedField(msg, 6),
    ratescoreList: jspb.Message.getRepeatedFloatingPointField(msg, 7),
    shopid: jspb.Message.getFieldWithDefault(msg, 8, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 9, ""),
    creditlevel: jspb.Message.getFieldWithDefault(msg, 10, 0),
    allitemcount: jspb.Message.getFieldWithDefault(msg, 11, 0),
    newitemcount: jspb.Message.getFieldWithDefault(msg, 12, 0),
    strfans: jspb.Message.getFieldWithDefault(msg, 13, ""),
    goodratepercentage: +jspb.Message.getFieldWithDefault(msg, 14, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.TmallShopInfo}
 */
proto.jarviscrawlercore.TmallShopInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.TmallShopInfo;
  return proto.jarviscrawlercore.TmallShopInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.TmallShopInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.TmallShopInfo}
 */
proto.jarviscrawlercore.TmallShopInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGold(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRank(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRating(value);
      break;
    case 6:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setRatelevelList(value);
      break;
    case 7:
      var value = /** @type {!Array<number>} */ (reader.readPackedFloat());
      msg.setRatescoreList(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setShopid(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCreditlevel(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAllitemcount(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNewitemcount(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrfans(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setGoodratepercentage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.TmallShopInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.TmallShopInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallShopInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGold();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRank();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRating();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getRatelevelList();
  if (f.length > 0) {
    writer.writePackedInt32(
      6,
      f
    );
  }
  f = message.getRatescoreList();
  if (f.length > 0) {
    writer.writePackedFloat(
      7,
      f
    );
  }
  f = message.getShopid();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCreditlevel();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getAllitemcount();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getNewitemcount();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getStrfans();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getGoodratepercentage();
  if (f !== 0.0) {
    writer.writeFloat(
      14,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool gold = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getGold = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setGold = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string url = 3;
 * @return {string}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setUrl = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string rank = 4;
 * @return {string}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getRank = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setRank = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 rating = 5;
 * @return {number}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getRating = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setRating = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated int32 rateLevel = 6;
 * @return {!Array<number>}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getRatelevelList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 6));
};


/** @param {!Array<number>} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setRatelevelList = function(value) {
  jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.addRatelevel = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


proto.jarviscrawlercore.TmallShopInfo.prototype.clearRatelevelList = function() {
  this.setRatelevelList([]);
};


/**
 * repeated float rateScore = 7;
 * @return {!Array<number>}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getRatescoreList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 7));
};


/** @param {!Array<number>} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setRatescoreList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.addRatescore = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


proto.jarviscrawlercore.TmallShopInfo.prototype.clearRatescoreList = function() {
  this.setRatescoreList([]);
};


/**
 * optional string shopid = 8;
 * @return {string}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getShopid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setShopid = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string userid = 9;
 * @return {string}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setUserid = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int32 creditLevel = 10;
 * @return {number}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getCreditlevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setCreditlevel = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 allItemCount = 11;
 * @return {number}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getAllitemcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setAllitemcount = function(value) {
  jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 newItemCount = 12;
 * @return {number}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getNewitemcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setNewitemcount = function(value) {
  jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string strFans = 13;
 * @return {string}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getStrfans = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setStrfans = function(value) {
  jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional float goodRatePercentage = 14;
 * @return {number}
 */
proto.jarviscrawlercore.TmallShopInfo.prototype.getGoodratepercentage = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 14, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallShopInfo.prototype.setGoodratepercentage = function(value) {
  jspb.Message.setProto3FloatField(this, 14, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.TmallProperty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jarviscrawlercore.TmallProperty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.TmallProperty.displayName = 'proto.jarviscrawlercore.TmallProperty';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.TmallProperty.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.TmallProperty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.TmallProperty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallProperty.toObject = function(includeInstance, msg) {
  var f, obj = {
    rootindex: jspb.Message.getFieldWithDefault(msg, 1, 0),
    rootname: jspb.Message.getFieldWithDefault(msg, 2, ""),
    key: jspb.Message.getFieldWithDefault(msg, 3, ""),
    value: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.TmallProperty}
 */
proto.jarviscrawlercore.TmallProperty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.TmallProperty;
  return proto.jarviscrawlercore.TmallProperty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.TmallProperty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.TmallProperty}
 */
proto.jarviscrawlercore.TmallProperty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRootindex(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRootname(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.TmallProperty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.TmallProperty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.TmallProperty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallProperty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRootindex();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getRootname();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional int32 rootIndex = 1;
 * @return {number}
 */
proto.jarviscrawlercore.TmallProperty.prototype.getRootindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallProperty.prototype.setRootindex = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string rootName = 2;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProperty.prototype.getRootname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProperty.prototype.setRootname = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string key = 3;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProperty.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProperty.prototype.setKey = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string value = 4;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProperty.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProperty.prototype.setValue = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.TmallProduct = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.TmallProduct.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.TmallProduct, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.TmallProduct.displayName = 'proto.jarviscrawlercore.TmallProduct';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.TmallProduct.repeatedFields_ = [2,10,14,19,21];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.TmallProduct.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.TmallProduct.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.TmallProduct} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallProduct.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    skusList: jspb.Message.toObjectList(msg.getSkusList(),
    proto.jarviscrawlercore.TmallSKUInfo.toObject, includeInstance),
    brand: jspb.Message.getFieldWithDefault(msg, 3, ""),
    brandid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    categoryid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    title: jspb.Message.getFieldWithDefault(msg, 6, ""),
    newinfo: jspb.Message.getFieldWithDefault(msg, 7, ""),
    reviews: jspb.Message.getFieldWithDefault(msg, 8, 0),
    rating: +jspb.Message.getFieldWithDefault(msg, 9, 0.0),
    reviewtagsList: jspb.Message.toObjectList(msg.getReviewtagsList(),
    proto.jarviscrawlercore.TmallReviewTag.toObject, includeInstance),
    lastupdatedtime: jspb.Message.getFieldWithDefault(msg, 11, 0),
    sellcount: jspb.Message.getFieldWithDefault(msg, 12, 0),
    strsellcount: jspb.Message.getFieldWithDefault(msg, 13, ""),
    lsthistoryList: jspb.Message.toObjectList(msg.getLsthistoryList(),
    proto.jarviscrawlercore.TmallProductHistory.toObject, includeInstance),
    rootcategoryid: jspb.Message.getFieldWithDefault(msg, 15, ""),
    tbitemid: jspb.Message.getFieldWithDefault(msg, 16, ""),
    brandvalueid: jspb.Message.getFieldWithDefault(msg, 17, ""),
    favcount: jspb.Message.getFieldWithDefault(msg, 18, 0),
    imgsList: jspb.Message.getRepeatedField(msg, 19),
    shop: (f = msg.getShop()) && proto.jarviscrawlercore.TmallShopInfo.toObject(includeInstance, f),
    propsList: jspb.Message.toObjectList(msg.getPropsList(),
    proto.jarviscrawlercore.TmallProperty.toObject, includeInstance),
    price: +jspb.Message.getFieldWithDefault(msg, 22, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.TmallProduct}
 */
proto.jarviscrawlercore.TmallProduct.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.TmallProduct;
  return proto.jarviscrawlercore.TmallProduct.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.TmallProduct} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.TmallProduct}
 */
proto.jarviscrawlercore.TmallProduct.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setItemid(value);
      break;
    case 2:
      var value = new proto.jarviscrawlercore.TmallSKUInfo;
      reader.readMessage(value,proto.jarviscrawlercore.TmallSKUInfo.deserializeBinaryFromReader);
      msg.addSkus(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrand(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrandid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategoryid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setNewinfo(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReviews(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRating(value);
      break;
    case 10:
      var value = new proto.jarviscrawlercore.TmallReviewTag;
      reader.readMessage(value,proto.jarviscrawlercore.TmallReviewTag.deserializeBinaryFromReader);
      msg.addReviewtags(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastupdatedtime(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSellcount(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrsellcount(value);
      break;
    case 14:
      var value = new proto.jarviscrawlercore.TmallProductHistory;
      reader.readMessage(value,proto.jarviscrawlercore.TmallProductHistory.deserializeBinaryFromReader);
      msg.addLsthistory(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setRootcategoryid(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setTbitemid(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrandvalueid(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFavcount(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.addImgs(value);
      break;
    case 20:
      var value = new proto.jarviscrawlercore.TmallShopInfo;
      reader.readMessage(value,proto.jarviscrawlercore.TmallShopInfo.deserializeBinaryFromReader);
      msg.setShop(value);
      break;
    case 21:
      var value = new proto.jarviscrawlercore.TmallProperty;
      reader.readMessage(value,proto.jarviscrawlercore.TmallProperty.deserializeBinaryFromReader);
      msg.addProps(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPrice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.TmallProduct.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.TmallProduct.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.TmallProduct} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.TmallProduct.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSkusList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.jarviscrawlercore.TmallSKUInfo.serializeBinaryToWriter
    );
  }
  f = message.getBrand();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBrandid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCategoryid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getNewinfo();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getReviews();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getRating();
  if (f !== 0.0) {
    writer.writeFloat(
      9,
      f
    );
  }
  f = message.getReviewtagsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.jarviscrawlercore.TmallReviewTag.serializeBinaryToWriter
    );
  }
  f = message.getLastupdatedtime();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = message.getSellcount();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getStrsellcount();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getLsthistoryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      proto.jarviscrawlercore.TmallProductHistory.serializeBinaryToWriter
    );
  }
  f = message.getRootcategoryid();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getTbitemid();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getBrandvalueid();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getFavcount();
  if (f !== 0) {
    writer.writeInt32(
      18,
      f
    );
  }
  f = message.getImgsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      19,
      f
    );
  }
  f = message.getShop();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      proto.jarviscrawlercore.TmallShopInfo.serializeBinaryToWriter
    );
  }
  f = message.getPropsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      21,
      f,
      proto.jarviscrawlercore.TmallProperty.serializeBinaryToWriter
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeFloat(
      22,
      f
    );
  }
};


/**
 * optional string itemID = 1;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getItemid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProduct.prototype.setItemid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated TmallSKUInfo skus = 2;
 * @return {!Array<!proto.jarviscrawlercore.TmallSKUInfo>}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getSkusList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.TmallSKUInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.TmallSKUInfo, 2));
};


/** @param {!Array<!proto.jarviscrawlercore.TmallSKUInfo>} value */
proto.jarviscrawlercore.TmallProduct.prototype.setSkusList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.jarviscrawlercore.TmallSKUInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.TmallSKUInfo}
 */
proto.jarviscrawlercore.TmallProduct.prototype.addSkus = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.jarviscrawlercore.TmallSKUInfo, opt_index);
};


proto.jarviscrawlercore.TmallProduct.prototype.clearSkusList = function() {
  this.setSkusList([]);
};


/**
 * optional string brand = 3;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProduct.prototype.setBrand = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string brandID = 4;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getBrandid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProduct.prototype.setBrandid = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string categoryID = 5;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getCategoryid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProduct.prototype.setCategoryid = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string title = 6;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProduct.prototype.setTitle = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string newinfo = 7;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getNewinfo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProduct.prototype.setNewinfo = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional int32 reviews = 8;
 * @return {number}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getReviews = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallProduct.prototype.setReviews = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional float rating = 9;
 * @return {number}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getRating = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 9, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallProduct.prototype.setRating = function(value) {
  jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * repeated TmallReviewTag reviewTags = 10;
 * @return {!Array<!proto.jarviscrawlercore.TmallReviewTag>}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getReviewtagsList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.TmallReviewTag>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.TmallReviewTag, 10));
};


/** @param {!Array<!proto.jarviscrawlercore.TmallReviewTag>} value */
proto.jarviscrawlercore.TmallProduct.prototype.setReviewtagsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.jarviscrawlercore.TmallReviewTag=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.TmallReviewTag}
 */
proto.jarviscrawlercore.TmallProduct.prototype.addReviewtags = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.jarviscrawlercore.TmallReviewTag, opt_index);
};


proto.jarviscrawlercore.TmallProduct.prototype.clearReviewtagsList = function() {
  this.setReviewtagsList([]);
};


/**
 * optional int64 lastUpdatedTime = 11;
 * @return {number}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getLastupdatedtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallProduct.prototype.setLastupdatedtime = function(value) {
  jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 sellCount = 12;
 * @return {number}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getSellcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallProduct.prototype.setSellcount = function(value) {
  jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string strSellCount = 13;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getStrsellcount = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProduct.prototype.setStrsellcount = function(value) {
  jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * repeated TmallProductHistory lstHistory = 14;
 * @return {!Array<!proto.jarviscrawlercore.TmallProductHistory>}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getLsthistoryList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.TmallProductHistory>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.TmallProductHistory, 14));
};


/** @param {!Array<!proto.jarviscrawlercore.TmallProductHistory>} value */
proto.jarviscrawlercore.TmallProduct.prototype.setLsthistoryList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.jarviscrawlercore.TmallProductHistory=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.TmallProductHistory}
 */
proto.jarviscrawlercore.TmallProduct.prototype.addLsthistory = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.jarviscrawlercore.TmallProductHistory, opt_index);
};


proto.jarviscrawlercore.TmallProduct.prototype.clearLsthistoryList = function() {
  this.setLsthistoryList([]);
};


/**
 * optional string rootCategoryID = 15;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getRootcategoryid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProduct.prototype.setRootcategoryid = function(value) {
  jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string tbItemID = 16;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getTbitemid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProduct.prototype.setTbitemid = function(value) {
  jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional string brandValueID = 17;
 * @return {string}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getBrandvalueid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.TmallProduct.prototype.setBrandvalueid = function(value) {
  jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional int32 favCount = 18;
 * @return {number}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getFavcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallProduct.prototype.setFavcount = function(value) {
  jspb.Message.setProto3IntField(this, 18, value);
};


/**
 * repeated string imgs = 19;
 * @return {!Array<string>}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getImgsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 19));
};


/** @param {!Array<string>} value */
proto.jarviscrawlercore.TmallProduct.prototype.setImgsList = function(value) {
  jspb.Message.setField(this, 19, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.jarviscrawlercore.TmallProduct.prototype.addImgs = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 19, value, opt_index);
};


proto.jarviscrawlercore.TmallProduct.prototype.clearImgsList = function() {
  this.setImgsList([]);
};


/**
 * optional TmallShopInfo shop = 20;
 * @return {?proto.jarviscrawlercore.TmallShopInfo}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getShop = function() {
  return /** @type{?proto.jarviscrawlercore.TmallShopInfo} */ (
    jspb.Message.getWrapperField(this, proto.jarviscrawlercore.TmallShopInfo, 20));
};


/** @param {?proto.jarviscrawlercore.TmallShopInfo|undefined} value */
proto.jarviscrawlercore.TmallProduct.prototype.setShop = function(value) {
  jspb.Message.setWrapperField(this, 20, value);
};


proto.jarviscrawlercore.TmallProduct.prototype.clearShop = function() {
  this.setShop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jarviscrawlercore.TmallProduct.prototype.hasShop = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * repeated TmallProperty props = 21;
 * @return {!Array<!proto.jarviscrawlercore.TmallProperty>}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getPropsList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.TmallProperty>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.TmallProperty, 21));
};


/** @param {!Array<!proto.jarviscrawlercore.TmallProperty>} value */
proto.jarviscrawlercore.TmallProduct.prototype.setPropsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 21, value);
};


/**
 * @param {!proto.jarviscrawlercore.TmallProperty=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.TmallProperty}
 */
proto.jarviscrawlercore.TmallProduct.prototype.addProps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 21, opt_value, proto.jarviscrawlercore.TmallProperty, opt_index);
};


proto.jarviscrawlercore.TmallProduct.prototype.clearPropsList = function() {
  this.setPropsList([]);
};


/**
 * optional float price = 22;
 * @return {number}
 */
proto.jarviscrawlercore.TmallProduct.prototype.getPrice = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 22, 0.0));
};


/** @param {number} value */
proto.jarviscrawlercore.TmallProduct.prototype.setPrice = function(value) {
  jspb.Message.setProto3FloatField(this, 22, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.RequestTmall = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jarviscrawlercore.RequestTmall, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.RequestTmall.displayName = 'proto.jarviscrawlercore.RequestTmall';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.RequestTmall.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.RequestTmall.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.RequestTmall} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.RequestTmall.toObject = function(includeInstance, msg) {
  var f, obj = {
    mode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    url: jspb.Message.getFieldWithDefault(msg, 2, ""),
    device: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.RequestTmall}
 */
proto.jarviscrawlercore.RequestTmall.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.RequestTmall;
  return proto.jarviscrawlercore.RequestTmall.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.RequestTmall} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.RequestTmall}
 */
proto.jarviscrawlercore.RequestTmall.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.jarviscrawlercore.TmallMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.RequestTmall.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.RequestTmall.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.RequestTmall} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.RequestTmall.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDevice();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional TmallMode mode = 1;
 * @return {!proto.jarviscrawlercore.TmallMode}
 */
proto.jarviscrawlercore.RequestTmall.prototype.getMode = function() {
  return /** @type {!proto.jarviscrawlercore.TmallMode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.jarviscrawlercore.TmallMode} value */
proto.jarviscrawlercore.RequestTmall.prototype.setMode = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string url = 2;
 * @return {string}
 */
proto.jarviscrawlercore.RequestTmall.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.RequestTmall.prototype.setUrl = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string device = 3;
 * @return {string}
 */
proto.jarviscrawlercore.RequestTmall.prototype.getDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.jarviscrawlercore.RequestTmall.prototype.setDevice = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.ReplyTmall = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.jarviscrawlercore.ReplyTmall.oneofGroups_);
};
goog.inherits(proto.jarviscrawlercore.ReplyTmall, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jarviscrawlercore.ReplyTmall.displayName = 'proto.jarviscrawlercore.ReplyTmall';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.jarviscrawlercore.ReplyTmall.oneofGroups_ = [[100]];

/**
 * @enum {number}
 */
proto.jarviscrawlercore.ReplyTmall.ReplyCase = {
  REPLY_NOT_SET: 0,
  PRODUCT: 100
};

/**
 * @return {proto.jarviscrawlercore.ReplyTmall.ReplyCase}
 */
proto.jarviscrawlercore.ReplyTmall.prototype.getReplyCase = function() {
  return /** @type {proto.jarviscrawlercore.ReplyTmall.ReplyCase} */(jspb.Message.computeOneofCase(this, proto.jarviscrawlercore.ReplyTmall.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.ReplyTmall.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.ReplyTmall.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.ReplyTmall} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ReplyTmall.toObject = function(includeInstance, msg) {
  var f, obj = {
    mode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    product: (f = msg.getProduct()) && proto.jarviscrawlercore.TmallProduct.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.ReplyTmall}
 */
proto.jarviscrawlercore.ReplyTmall.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.ReplyTmall;
  return proto.jarviscrawlercore.ReplyTmall.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.ReplyTmall} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.ReplyTmall}
 */
proto.jarviscrawlercore.ReplyTmall.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.jarviscrawlercore.TmallMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    case 100:
      var value = new proto.jarviscrawlercore.TmallProduct;
      reader.readMessage(value,proto.jarviscrawlercore.TmallProduct.deserializeBinaryFromReader);
      msg.setProduct(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.ReplyTmall.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.ReplyTmall.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.ReplyTmall} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ReplyTmall.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getProduct();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.jarviscrawlercore.TmallProduct.serializeBinaryToWriter
    );
  }
};


/**
 * optional TmallMode mode = 1;
 * @return {!proto.jarviscrawlercore.TmallMode}
 */
proto.jarviscrawlercore.ReplyTmall.prototype.getMode = function() {
  return /** @type {!proto.jarviscrawlercore.TmallMode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.jarviscrawlercore.TmallMode} value */
proto.jarviscrawlercore.ReplyTmall.prototype.setMode = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional TmallProduct product = 100;
 * @return {?proto.jarviscrawlercore.TmallProduct}
 */
proto.jarviscrawlercore.ReplyTmall.prototype.getProduct = function() {
  return /** @type{?proto.jarviscrawlercore.TmallProduct} */ (
    jspb.Message.getWrapperField(this, proto.jarviscrawlercore.TmallProduct, 100));
};


/** @param {?proto.jarviscrawlercore.TmallProduct|undefined} value */
proto.jarviscrawlercore.ReplyTmall.prototype.setProduct = function(value) {
  jspb.Message.setOneofWrapperField(this, 100, proto.jarviscrawlercore.ReplyTmall.oneofGroups_[0], value);
};


proto.jarviscrawlercore.ReplyTmall.prototype.clearProduct = function() {
  this.setProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jarviscrawlercore.ReplyTmall.prototype.hasProduct = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * @enum {number}
 */
proto.jarviscrawlercore.TmallMode = {
  TMM_PRODUCT: 0,
  TMM_MOBILEPRODUCT: 1
};

goog.object.extend(exports, proto.jarviscrawlercore);
