// source: manhuadb.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.jarviscrawlercore.ManhuaDBAuthor', null, global);
goog.exportSymbol('proto.jarviscrawlercore.ManhuaDBBook', null, global);
goog.exportSymbol('proto.jarviscrawlercore.ManhuaDBBookInfo', null, global);
goog.exportSymbol('proto.jarviscrawlercore.ManhuaDBManhua', null, global);
goog.exportSymbol('proto.jarviscrawlercore.ManhuaDBMode', null, global);
goog.exportSymbol('proto.jarviscrawlercore.ManhuaDBPage', null, global);
goog.exportSymbol('proto.jarviscrawlercore.ReplyManhuaDB', null, global);
goog.exportSymbol('proto.jarviscrawlercore.ReplyManhuaDB.ReplyCase', null, global);
goog.exportSymbol('proto.jarviscrawlercore.RequestManhuaDB', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.ManhuaDBBook = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jarviscrawlercore.ManhuaDBBook, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.ManhuaDBBook.displayName = 'proto.jarviscrawlercore.ManhuaDBBook';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.ManhuaDBManhua = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.ManhuaDBManhua.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.ManhuaDBManhua, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.ManhuaDBManhua.displayName = 'proto.jarviscrawlercore.ManhuaDBManhua';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.ManhuaDBAuthor = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.ManhuaDBAuthor.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.ManhuaDBAuthor, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.ManhuaDBAuthor.displayName = 'proto.jarviscrawlercore.ManhuaDBAuthor';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.ManhuaDBPage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jarviscrawlercore.ManhuaDBPage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.ManhuaDBPage.displayName = 'proto.jarviscrawlercore.ManhuaDBPage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.ManhuaDBBookInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.ManhuaDBBookInfo.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.ManhuaDBBookInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.ManhuaDBBookInfo.displayName = 'proto.jarviscrawlercore.ManhuaDBBookInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.RequestManhuaDB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jarviscrawlercore.RequestManhuaDB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.RequestManhuaDB.displayName = 'proto.jarviscrawlercore.RequestManhuaDB';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.ReplyManhuaDB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.jarviscrawlercore.ReplyManhuaDB.oneofGroups_);
};
goog.inherits(proto.jarviscrawlercore.ReplyManhuaDB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.ReplyManhuaDB.displayName = 'proto.jarviscrawlercore.ReplyManhuaDB';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.ManhuaDBBook.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.ManhuaDBBook} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ManhuaDBBook.toObject = function(includeInstance, msg) {
  var f, obj = {
    title: jspb.Message.getFieldWithDefault(msg, 1, ""),
    url: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    roottype: jspb.Message.getFieldWithDefault(msg, 4, 0),
    rootname: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.ManhuaDBBook}
 */
proto.jarviscrawlercore.ManhuaDBBook.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.ManhuaDBBook;
  return proto.jarviscrawlercore.ManhuaDBBook.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.ManhuaDBBook} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.ManhuaDBBook}
 */
proto.jarviscrawlercore.ManhuaDBBook.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRoottype(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRootname(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.ManhuaDBBook.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.ManhuaDBBook} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ManhuaDBBook.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRoottype();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getRootname();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string title = 1;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBBook} returns this
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string url = 2;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBBook} returns this
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBBook} returns this
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 rootType = 4;
 * @return {number}
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.getRoottype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.ManhuaDBBook} returns this
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.setRoottype = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string rootName = 5;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.getRootname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBBook} returns this
 */
proto.jarviscrawlercore.ManhuaDBBook.prototype.setRootname = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.ManhuaDBManhua.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.ManhuaDBManhua.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.ManhuaDBManhua} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ManhuaDBManhua.toObject = function(includeInstance, msg) {
  var f, obj = {
    comicid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    booksList: jspb.Message.toObjectList(msg.getBooksList(),
    proto.jarviscrawlercore.ManhuaDBBook.toObject, includeInstance),
    authorsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    url: jspb.Message.getFieldWithDefault(msg, 5, ""),
    cover: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua}
 */
proto.jarviscrawlercore.ManhuaDBManhua.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.ManhuaDBManhua;
  return proto.jarviscrawlercore.ManhuaDBManhua.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.ManhuaDBManhua} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua}
 */
proto.jarviscrawlercore.ManhuaDBManhua.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setComicid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = new proto.jarviscrawlercore.ManhuaDBBook;
      reader.readMessage(value,proto.jarviscrawlercore.ManhuaDBBook.deserializeBinaryFromReader);
      msg.addBooks(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addAuthors(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCover(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.ManhuaDBManhua.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.ManhuaDBManhua} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ManhuaDBManhua.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getComicid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBooksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.jarviscrawlercore.ManhuaDBBook.serializeBinaryToWriter
    );
  }
  f = message.getAuthorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCover();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string comicid = 1;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.getComicid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua} returns this
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.setComicid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua} returns this
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated ManhuaDBBook books = 3;
 * @return {!Array<!proto.jarviscrawlercore.ManhuaDBBook>}
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.getBooksList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.ManhuaDBBook>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.ManhuaDBBook, 3));
};


/**
 * @param {!Array<!proto.jarviscrawlercore.ManhuaDBBook>} value
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua} returns this
*/
proto.jarviscrawlercore.ManhuaDBManhua.prototype.setBooksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.jarviscrawlercore.ManhuaDBBook=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.ManhuaDBBook}
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.addBooks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.jarviscrawlercore.ManhuaDBBook, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua} returns this
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.clearBooksList = function() {
  return this.setBooksList([]);
};


/**
 * repeated string authors = 4;
 * @return {!Array<string>}
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.getAuthorsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua} returns this
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.setAuthorsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua} returns this
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.addAuthors = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua} returns this
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.clearAuthorsList = function() {
  return this.setAuthorsList([]);
};


/**
 * optional string url = 5;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua} returns this
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string cover = 6;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.getCover = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua} returns this
 */
proto.jarviscrawlercore.ManhuaDBManhua.prototype.setCover = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.ManhuaDBAuthor.repeatedFields_ = [2,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.ManhuaDBAuthor.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.ManhuaDBAuthor} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ManhuaDBAuthor.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    othernameList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    detail: jspb.Message.getFieldWithDefault(msg, 3, ""),
    manhuaList: jspb.Message.toObjectList(msg.getManhuaList(),
    proto.jarviscrawlercore.ManhuaDBManhua.toObject, includeInstance),
    authorid: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.ManhuaDBAuthor}
 */
proto.jarviscrawlercore.ManhuaDBAuthor.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.ManhuaDBAuthor;
  return proto.jarviscrawlercore.ManhuaDBAuthor.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.ManhuaDBAuthor} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.ManhuaDBAuthor}
 */
proto.jarviscrawlercore.ManhuaDBAuthor.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addOthername(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetail(value);
      break;
    case 4:
      var value = new proto.jarviscrawlercore.ManhuaDBManhua;
      reader.readMessage(value,proto.jarviscrawlercore.ManhuaDBManhua.deserializeBinaryFromReader);
      msg.addManhua(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthorid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.ManhuaDBAuthor.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.ManhuaDBAuthor} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ManhuaDBAuthor.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOthernameList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getDetail();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getManhuaList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.jarviscrawlercore.ManhuaDBManhua.serializeBinaryToWriter
    );
  }
  f = message.getAuthorid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBAuthor} returns this
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string otherName = 2;
 * @return {!Array<string>}
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.getOthernameList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.jarviscrawlercore.ManhuaDBAuthor} returns this
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.setOthernameList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.ManhuaDBAuthor} returns this
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.addOthername = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.ManhuaDBAuthor} returns this
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.clearOthernameList = function() {
  return this.setOthernameList([]);
};


/**
 * optional string detail = 3;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.getDetail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBAuthor} returns this
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.setDetail = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated ManhuaDBManhua manhua = 4;
 * @return {!Array<!proto.jarviscrawlercore.ManhuaDBManhua>}
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.getManhuaList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.ManhuaDBManhua>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.ManhuaDBManhua, 4));
};


/**
 * @param {!Array<!proto.jarviscrawlercore.ManhuaDBManhua>} value
 * @return {!proto.jarviscrawlercore.ManhuaDBAuthor} returns this
*/
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.setManhuaList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.jarviscrawlercore.ManhuaDBManhua=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.ManhuaDBManhua}
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.addManhua = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.jarviscrawlercore.ManhuaDBManhua, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.ManhuaDBAuthor} returns this
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.clearManhuaList = function() {
  return this.setManhuaList([]);
};


/**
 * optional string authorid = 5;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.getAuthorid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBAuthor} returns this
 */
proto.jarviscrawlercore.ManhuaDBAuthor.prototype.setAuthorid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.ManhuaDBPage.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.ManhuaDBPage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.ManhuaDBPage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ManhuaDBPage.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    pageindex: jspb.Message.getFieldWithDefault(msg, 2, 0),
    data: msg.getData_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.ManhuaDBPage}
 */
proto.jarviscrawlercore.ManhuaDBPage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.ManhuaDBPage;
  return proto.jarviscrawlercore.ManhuaDBPage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.ManhuaDBPage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.ManhuaDBPage}
 */
proto.jarviscrawlercore.ManhuaDBPage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageindex(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.ManhuaDBPage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.ManhuaDBPage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.ManhuaDBPage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ManhuaDBPage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPageindex();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBPage.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBPage} returns this
 */
proto.jarviscrawlercore.ManhuaDBPage.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 pageIndex = 2;
 * @return {number}
 */
proto.jarviscrawlercore.ManhuaDBPage.prototype.getPageindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.ManhuaDBPage} returns this
 */
proto.jarviscrawlercore.ManhuaDBPage.prototype.setPageindex = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional bytes data = 3;
 * @return {!(string|Uint8Array)}
 */
proto.jarviscrawlercore.ManhuaDBPage.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes data = 3;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBPage.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.ManhuaDBPage.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.jarviscrawlercore.ManhuaDBPage} returns this
 */
proto.jarviscrawlercore.ManhuaDBPage.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.ManhuaDBBookInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.ManhuaDBBookInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    comicid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bookid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    pagesList: jspb.Message.toObjectList(msg.getPagesList(),
    proto.jarviscrawlercore.ManhuaDBPage.toObject, includeInstance),
    pagenums: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.ManhuaDBBookInfo}
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.ManhuaDBBookInfo;
  return proto.jarviscrawlercore.ManhuaDBBookInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.ManhuaDBBookInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.ManhuaDBBookInfo}
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setComicid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBookid(value);
      break;
    case 3:
      var value = new proto.jarviscrawlercore.ManhuaDBPage;
      reader.readMessage(value,proto.jarviscrawlercore.ManhuaDBPage.deserializeBinaryFromReader);
      msg.addPages(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPagenums(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.ManhuaDBBookInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.ManhuaDBBookInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getComicid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBookid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.jarviscrawlercore.ManhuaDBPage.serializeBinaryToWriter
    );
  }
  f = message.getPagenums();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string comicid = 1;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.getComicid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBBookInfo} returns this
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.setComicid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string bookid = 2;
 * @return {string}
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.getBookid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.ManhuaDBBookInfo} returns this
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.setBookid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated ManhuaDBPage pages = 3;
 * @return {!Array<!proto.jarviscrawlercore.ManhuaDBPage>}
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.getPagesList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.ManhuaDBPage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.ManhuaDBPage, 3));
};


/**
 * @param {!Array<!proto.jarviscrawlercore.ManhuaDBPage>} value
 * @return {!proto.jarviscrawlercore.ManhuaDBBookInfo} returns this
*/
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.setPagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.jarviscrawlercore.ManhuaDBPage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.ManhuaDBPage}
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.addPages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.jarviscrawlercore.ManhuaDBPage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.ManhuaDBBookInfo} returns this
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.clearPagesList = function() {
  return this.setPagesList([]);
};


/**
 * optional int32 pageNums = 4;
 * @return {number}
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.getPagenums = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.ManhuaDBBookInfo} returns this
 */
proto.jarviscrawlercore.ManhuaDBBookInfo.prototype.setPagenums = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.RequestManhuaDB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.RequestManhuaDB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.RequestManhuaDB.toObject = function(includeInstance, msg) {
  var f, obj = {
    mode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    comicid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    bookid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    pageindex: jspb.Message.getFieldWithDefault(msg, 4, 0),
    authorid: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.RequestManhuaDB}
 */
proto.jarviscrawlercore.RequestManhuaDB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.RequestManhuaDB;
  return proto.jarviscrawlercore.RequestManhuaDB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.RequestManhuaDB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.RequestManhuaDB}
 */
proto.jarviscrawlercore.RequestManhuaDB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.jarviscrawlercore.ManhuaDBMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setComicid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBookid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageindex(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthorid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.RequestManhuaDB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.RequestManhuaDB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.RequestManhuaDB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getComicid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBookid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPageindex();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getAuthorid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional ManhuaDBMode mode = 1;
 * @return {!proto.jarviscrawlercore.ManhuaDBMode}
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.getMode = function() {
  return /** @type {!proto.jarviscrawlercore.ManhuaDBMode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.jarviscrawlercore.ManhuaDBMode} value
 * @return {!proto.jarviscrawlercore.RequestManhuaDB} returns this
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.setMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string comicid = 2;
 * @return {string}
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.getComicid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.RequestManhuaDB} returns this
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.setComicid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string bookid = 3;
 * @return {string}
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.getBookid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.RequestManhuaDB} returns this
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.setBookid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 pageIndex = 4;
 * @return {number}
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.getPageindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.RequestManhuaDB} returns this
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.setPageindex = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string authorid = 5;
 * @return {string}
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.getAuthorid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.RequestManhuaDB} returns this
 */
proto.jarviscrawlercore.RequestManhuaDB.prototype.setAuthorid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.jarviscrawlercore.ReplyManhuaDB.oneofGroups_ = [[100,101,102]];

/**
 * @enum {number}
 */
proto.jarviscrawlercore.ReplyManhuaDB.ReplyCase = {
  REPLY_NOT_SET: 0,
  MANHUA: 100,
  BOOK: 101,
  AUTHOR: 102
};

/**
 * @return {proto.jarviscrawlercore.ReplyManhuaDB.ReplyCase}
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.getReplyCase = function() {
  return /** @type {proto.jarviscrawlercore.ReplyManhuaDB.ReplyCase} */(jspb.Message.computeOneofCase(this, proto.jarviscrawlercore.ReplyManhuaDB.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.ReplyManhuaDB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.ReplyManhuaDB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ReplyManhuaDB.toObject = function(includeInstance, msg) {
  var f, obj = {
    mode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    manhua: (f = msg.getManhua()) && proto.jarviscrawlercore.ManhuaDBManhua.toObject(includeInstance, f),
    book: (f = msg.getBook()) && proto.jarviscrawlercore.ManhuaDBBookInfo.toObject(includeInstance, f),
    author: (f = msg.getAuthor()) && proto.jarviscrawlercore.ManhuaDBAuthor.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.ReplyManhuaDB}
 */
proto.jarviscrawlercore.ReplyManhuaDB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.ReplyManhuaDB;
  return proto.jarviscrawlercore.ReplyManhuaDB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.ReplyManhuaDB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.ReplyManhuaDB}
 */
proto.jarviscrawlercore.ReplyManhuaDB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.jarviscrawlercore.ManhuaDBMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    case 100:
      var value = new proto.jarviscrawlercore.ManhuaDBManhua;
      reader.readMessage(value,proto.jarviscrawlercore.ManhuaDBManhua.deserializeBinaryFromReader);
      msg.setManhua(value);
      break;
    case 101:
      var value = new proto.jarviscrawlercore.ManhuaDBBookInfo;
      reader.readMessage(value,proto.jarviscrawlercore.ManhuaDBBookInfo.deserializeBinaryFromReader);
      msg.setBook(value);
      break;
    case 102:
      var value = new proto.jarviscrawlercore.ManhuaDBAuthor;
      reader.readMessage(value,proto.jarviscrawlercore.ManhuaDBAuthor.deserializeBinaryFromReader);
      msg.setAuthor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.ReplyManhuaDB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.ReplyManhuaDB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ReplyManhuaDB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getManhua();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.jarviscrawlercore.ManhuaDBManhua.serializeBinaryToWriter
    );
  }
  f = message.getBook();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      proto.jarviscrawlercore.ManhuaDBBookInfo.serializeBinaryToWriter
    );
  }
  f = message.getAuthor();
  if (f != null) {
    writer.writeMessage(
      102,
      f,
      proto.jarviscrawlercore.ManhuaDBAuthor.serializeBinaryToWriter
    );
  }
};


/**
 * optional ManhuaDBMode mode = 1;
 * @return {!proto.jarviscrawlercore.ManhuaDBMode}
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.getMode = function() {
  return /** @type {!proto.jarviscrawlercore.ManhuaDBMode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.jarviscrawlercore.ManhuaDBMode} value
 * @return {!proto.jarviscrawlercore.ReplyManhuaDB} returns this
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.setMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional ManhuaDBManhua manhua = 100;
 * @return {?proto.jarviscrawlercore.ManhuaDBManhua}
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.getManhua = function() {
  return /** @type{?proto.jarviscrawlercore.ManhuaDBManhua} */ (
    jspb.Message.getWrapperField(this, proto.jarviscrawlercore.ManhuaDBManhua, 100));
};


/**
 * @param {?proto.jarviscrawlercore.ManhuaDBManhua|undefined} value
 * @return {!proto.jarviscrawlercore.ReplyManhuaDB} returns this
*/
proto.jarviscrawlercore.ReplyManhuaDB.prototype.setManhua = function(value) {
  return jspb.Message.setOneofWrapperField(this, 100, proto.jarviscrawlercore.ReplyManhuaDB.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jarviscrawlercore.ReplyManhuaDB} returns this
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.clearManhua = function() {
  return this.setManhua(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.hasManhua = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional ManhuaDBBookInfo book = 101;
 * @return {?proto.jarviscrawlercore.ManhuaDBBookInfo}
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.getBook = function() {
  return /** @type{?proto.jarviscrawlercore.ManhuaDBBookInfo} */ (
    jspb.Message.getWrapperField(this, proto.jarviscrawlercore.ManhuaDBBookInfo, 101));
};


/**
 * @param {?proto.jarviscrawlercore.ManhuaDBBookInfo|undefined} value
 * @return {!proto.jarviscrawlercore.ReplyManhuaDB} returns this
*/
proto.jarviscrawlercore.ReplyManhuaDB.prototype.setBook = function(value) {
  return jspb.Message.setOneofWrapperField(this, 101, proto.jarviscrawlercore.ReplyManhuaDB.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jarviscrawlercore.ReplyManhuaDB} returns this
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.clearBook = function() {
  return this.setBook(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.hasBook = function() {
  return jspb.Message.getField(this, 101) != null;
};


/**
 * optional ManhuaDBAuthor author = 102;
 * @return {?proto.jarviscrawlercore.ManhuaDBAuthor}
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.getAuthor = function() {
  return /** @type{?proto.jarviscrawlercore.ManhuaDBAuthor} */ (
    jspb.Message.getWrapperField(this, proto.jarviscrawlercore.ManhuaDBAuthor, 102));
};


/**
 * @param {?proto.jarviscrawlercore.ManhuaDBAuthor|undefined} value
 * @return {!proto.jarviscrawlercore.ReplyManhuaDB} returns this
*/
proto.jarviscrawlercore.ReplyManhuaDB.prototype.setAuthor = function(value) {
  return jspb.Message.setOneofWrapperField(this, 102, proto.jarviscrawlercore.ReplyManhuaDB.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jarviscrawlercore.ReplyManhuaDB} returns this
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.clearAuthor = function() {
  return this.setAuthor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jarviscrawlercore.ReplyManhuaDB.prototype.hasAuthor = function() {
  return jspb.Message.getField(this, 102) != null;
};


/**
 * @enum {number}
 */
proto.jarviscrawlercore.ManhuaDBMode = {
  MHDB_MANHUA: 0,
  MHDB_BOOK: 1,
  MHDB_AUTHOR: 2
};

goog.object.extend(exports, proto.jarviscrawlercore);
