// source: mountainsteals.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.jarviscrawlercore.MountainStealsColorSize', null, global);
goog.exportSymbol('proto.jarviscrawlercore.MountainStealsHistory', null, global);
goog.exportSymbol('proto.jarviscrawlercore.MountainStealsMode', null, global);
goog.exportSymbol('proto.jarviscrawlercore.MountainStealsProduct', null, global);
goog.exportSymbol('proto.jarviscrawlercore.MountainStealsSale', null, global);
goog.exportSymbol('proto.jarviscrawlercore.ReplyMountainSteals', null, global);
goog.exportSymbol('proto.jarviscrawlercore.ReplyMountainSteals.ReplyCase', null, global);
goog.exportSymbol('proto.jarviscrawlercore.RequestMountainSteals', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.MountainStealsSale = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.MountainStealsSale.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.MountainStealsSale, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.MountainStealsSale.displayName = 'proto.jarviscrawlercore.MountainStealsSale';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.MountainStealsColorSize = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jarviscrawlercore.MountainStealsColorSize, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.MountainStealsColorSize.displayName = 'proto.jarviscrawlercore.MountainStealsColorSize';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.MountainStealsHistory = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.MountainStealsHistory.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.MountainStealsHistory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.MountainStealsHistory.displayName = 'proto.jarviscrawlercore.MountainStealsHistory';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.MountainStealsProduct = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jarviscrawlercore.MountainStealsProduct.repeatedFields_, null);
};
goog.inherits(proto.jarviscrawlercore.MountainStealsProduct, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.MountainStealsProduct.displayName = 'proto.jarviscrawlercore.MountainStealsProduct';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.RequestMountainSteals = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jarviscrawlercore.RequestMountainSteals, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.RequestMountainSteals.displayName = 'proto.jarviscrawlercore.RequestMountainSteals';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jarviscrawlercore.ReplyMountainSteals = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.jarviscrawlercore.ReplyMountainSteals.oneofGroups_);
};
goog.inherits(proto.jarviscrawlercore.ReplyMountainSteals, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jarviscrawlercore.ReplyMountainSteals.displayName = 'proto.jarviscrawlercore.ReplyMountainSteals';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.MountainStealsSale.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.MountainStealsSale.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.MountainStealsSale} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.MountainStealsSale.toObject = function(includeInstance, msg) {
  var f, obj = {
    productsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    saleurl: jspb.Message.getFieldWithDefault(msg, 2, ""),
    code: jspb.Message.getFieldWithDefault(msg, 3, ""),
    lastupdatedtime: jspb.Message.getFieldWithDefault(msg, 4, 0),
    createtime: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.MountainStealsSale}
 */
proto.jarviscrawlercore.MountainStealsSale.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.MountainStealsSale;
  return proto.jarviscrawlercore.MountainStealsSale.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.MountainStealsSale} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.MountainStealsSale}
 */
proto.jarviscrawlercore.MountainStealsSale.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addProducts(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSaleurl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastupdatedtime(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatetime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.MountainStealsSale.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.MountainStealsSale} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.MountainStealsSale.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProductsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getSaleurl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLastupdatedtime();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getCreatetime();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * repeated string products = 1;
 * @return {!Array<string>}
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.getProductsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.jarviscrawlercore.MountainStealsSale} returns this
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.setProductsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.MountainStealsSale} returns this
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.addProducts = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.MountainStealsSale} returns this
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.clearProductsList = function() {
  return this.setProductsList([]);
};


/**
 * optional string saleurl = 2;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.getSaleurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsSale} returns this
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.setSaleurl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string code = 3;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsSale} returns this
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 lastUpdatedTime = 4;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.getLastupdatedtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsSale} returns this
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.setLastupdatedtime = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 createTime = 5;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.getCreatetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsSale} returns this
 */
proto.jarviscrawlercore.MountainStealsSale.prototype.setCreatetime = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.MountainStealsColorSize.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.MountainStealsColorSize} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.MountainStealsColorSize.toObject = function(includeInstance, msg) {
  var f, obj = {
    color: jspb.Message.getFieldWithDefault(msg, 1, ""),
    size: jspb.Message.getFieldWithDefault(msg, 2, ""),
    price: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    img: jspb.Message.getFieldWithDefault(msg, 4, ""),
    sku: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.MountainStealsColorSize}
 */
proto.jarviscrawlercore.MountainStealsColorSize.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.MountainStealsColorSize;
  return proto.jarviscrawlercore.MountainStealsColorSize.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.MountainStealsColorSize} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.MountainStealsColorSize}
 */
proto.jarviscrawlercore.MountainStealsColorSize.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setColor(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSize(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPrice(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setImg(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.MountainStealsColorSize.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.MountainStealsColorSize} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.MountainStealsColorSize.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getColor();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSize();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getImg();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string color = 1;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.getColor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsColorSize} returns this
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.setColor = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string size = 2;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.getSize = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsColorSize} returns this
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.setSize = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional float price = 3;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsColorSize} returns this
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional string img = 4;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.getImg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsColorSize} returns this
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.setImg = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string sku = 5;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsColorSize} returns this
 */
proto.jarviscrawlercore.MountainStealsColorSize.prototype.setSku = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.MountainStealsHistory.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.MountainStealsHistory.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.MountainStealsHistory} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.MountainStealsHistory.toObject = function(includeInstance, msg) {
  var f, obj = {
    updatetime: jspb.Message.getFieldWithDefault(msg, 1, 0),
    price: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    curprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    stocklevel: jspb.Message.getFieldWithDefault(msg, 4, 0),
    salecode: jspb.Message.getFieldWithDefault(msg, 5, ""),
    offersList: jspb.Message.toObjectList(msg.getOffersList(),
    proto.jarviscrawlercore.MountainStealsColorSize.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.MountainStealsHistory}
 */
proto.jarviscrawlercore.MountainStealsHistory.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.MountainStealsHistory;
  return proto.jarviscrawlercore.MountainStealsHistory.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.MountainStealsHistory} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.MountainStealsHistory}
 */
proto.jarviscrawlercore.MountainStealsHistory.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatetime(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPrice(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setCurprice(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStocklevel(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSalecode(value);
      break;
    case 6:
      var value = new proto.jarviscrawlercore.MountainStealsColorSize;
      reader.readMessage(value,proto.jarviscrawlercore.MountainStealsColorSize.deserializeBinaryFromReader);
      msg.addOffers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.MountainStealsHistory.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.MountainStealsHistory} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.MountainStealsHistory.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpdatetime();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getCurprice();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getStocklevel();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSalecode();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getOffersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.jarviscrawlercore.MountainStealsColorSize.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 updateTime = 1;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.getUpdatetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsHistory} returns this
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.setUpdatetime = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional float price = 2;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsHistory} returns this
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float curPrice = 3;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.getCurprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsHistory} returns this
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.setCurprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional int32 stockLevel = 4;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.getStocklevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsHistory} returns this
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.setStocklevel = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string saleCode = 5;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.getSalecode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsHistory} returns this
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.setSalecode = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated MountainStealsColorSize offers = 6;
 * @return {!Array<!proto.jarviscrawlercore.MountainStealsColorSize>}
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.getOffersList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.MountainStealsColorSize>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.MountainStealsColorSize, 6));
};


/**
 * @param {!Array<!proto.jarviscrawlercore.MountainStealsColorSize>} value
 * @return {!proto.jarviscrawlercore.MountainStealsHistory} returns this
*/
proto.jarviscrawlercore.MountainStealsHistory.prototype.setOffersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.jarviscrawlercore.MountainStealsColorSize=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.MountainStealsColorSize}
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.addOffers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.jarviscrawlercore.MountainStealsColorSize, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.MountainStealsHistory} returns this
 */
proto.jarviscrawlercore.MountainStealsHistory.prototype.clearOffersList = function() {
  return this.setOffersList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jarviscrawlercore.MountainStealsProduct.repeatedFields_ = [3,6,7,13,17];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.MountainStealsProduct.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.MountainStealsProduct} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.MountainStealsProduct.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    categoryList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    brand: jspb.Message.getFieldWithDefault(msg, 4, ""),
    rating: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    colorsizeList: jspb.Message.toObjectList(msg.getColorsizeList(),
    proto.jarviscrawlercore.MountainStealsColorSize.toObject, includeInstance),
    imagesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    price: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    minprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    maxprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    details: jspb.Message.getFieldWithDefault(msg, 11, ""),
    spec: jspb.Message.getFieldWithDefault(msg, 12, ""),
    ratingcountList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    mapradingMap: (f = msg.getMapradingMap()) ? f.toObject(includeInstance, undefined) : [],
    sizegiud: jspb.Message.getFieldWithDefault(msg, 15, ""),
    lastupdatedtime: jspb.Message.getFieldWithDefault(msg, 16, 0),
    lsthistoryList: jspb.Message.toObjectList(msg.getLsthistoryList(),
    proto.jarviscrawlercore.MountainStealsHistory.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.MountainStealsProduct}
 */
proto.jarviscrawlercore.MountainStealsProduct.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.MountainStealsProduct;
  return proto.jarviscrawlercore.MountainStealsProduct.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.MountainStealsProduct} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.MountainStealsProduct}
 */
proto.jarviscrawlercore.MountainStealsProduct.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addCategory(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrand(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRating(value);
      break;
    case 6:
      var value = new proto.jarviscrawlercore.MountainStealsColorSize;
      reader.readMessage(value,proto.jarviscrawlercore.MountainStealsColorSize.deserializeBinaryFromReader);
      msg.addColorsize(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addImages(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPrice(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMinprice(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMaxprice(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetails(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpec(value);
      break;
    case 13:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRatingcount(values[i]);
      }
      break;
    case 14:
      var value = msg.getMapradingMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readFloat, null, "", 0.0);
         });
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setSizegiud(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastupdatedtime(value);
      break;
    case 17:
      var value = new proto.jarviscrawlercore.MountainStealsHistory;
      reader.readMessage(value,proto.jarviscrawlercore.MountainStealsHistory.deserializeBinaryFromReader);
      msg.addLsthistory(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.MountainStealsProduct.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.MountainStealsProduct} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.MountainStealsProduct.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCategoryList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getBrand();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRating();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getColorsizeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.jarviscrawlercore.MountainStealsColorSize.serializeBinaryToWriter
    );
  }
  f = message.getImagesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getMinprice();
  if (f !== 0.0) {
    writer.writeFloat(
      9,
      f
    );
  }
  f = message.getMaxprice();
  if (f !== 0.0) {
    writer.writeFloat(
      10,
      f
    );
  }
  f = message.getDetails();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getSpec();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getRatingcountList();
  if (f.length > 0) {
    writer.writePackedInt32(
      13,
      f
    );
  }
  f = message.getMapradingMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(14, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeFloat);
  }
  f = message.getSizegiud();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getLastupdatedtime();
  if (f !== 0) {
    writer.writeInt64(
      16,
      f
    );
  }
  f = message.getLsthistoryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      17,
      f,
      proto.jarviscrawlercore.MountainStealsHistory.serializeBinaryToWriter
    );
  }
};


/**
 * optional string code = 1;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string category = 3;
 * @return {!Array<string>}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getCategoryList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setCategoryList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.addCategory = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.clearCategoryList = function() {
  return this.setCategoryList([]);
};


/**
 * optional string brand = 4;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setBrand = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional float rating = 5;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getRating = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setRating = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * repeated MountainStealsColorSize colorSize = 6;
 * @return {!Array<!proto.jarviscrawlercore.MountainStealsColorSize>}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getColorsizeList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.MountainStealsColorSize>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.MountainStealsColorSize, 6));
};


/**
 * @param {!Array<!proto.jarviscrawlercore.MountainStealsColorSize>} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
*/
proto.jarviscrawlercore.MountainStealsProduct.prototype.setColorsizeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.jarviscrawlercore.MountainStealsColorSize=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.MountainStealsColorSize}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.addColorsize = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.jarviscrawlercore.MountainStealsColorSize, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.clearColorsizeList = function() {
  return this.setColorsizeList([]);
};


/**
 * repeated string images = 7;
 * @return {!Array<string>}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getImagesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setImagesList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.addImages = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.clearImagesList = function() {
  return this.setImagesList([]);
};


/**
 * optional float price = 8;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional float minPrice = 9;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getMinprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setMinprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional float maxPrice = 10;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getMaxprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setMaxprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional string details = 11;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getDetails = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setDetails = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string spec = 12;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getSpec = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setSpec = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * repeated int32 ratingCount = 13;
 * @return {!Array<number>}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getRatingcountList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 13));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setRatingcountList = function(value) {
  return jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.addRatingcount = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.clearRatingcountList = function() {
  return this.setRatingcountList([]);
};


/**
 * map<string, float> mapRading = 14;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getMapradingMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 14, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.clearMapradingMap = function() {
  this.getMapradingMap().clear();
  return this;};


/**
 * optional string sizeGiud = 15;
 * @return {string}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getSizegiud = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setSizegiud = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional int64 lastUpdatedTime = 16;
 * @return {number}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getLastupdatedtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.setLastupdatedtime = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * repeated MountainStealsHistory lstHistory = 17;
 * @return {!Array<!proto.jarviscrawlercore.MountainStealsHistory>}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.getLsthistoryList = function() {
  return /** @type{!Array<!proto.jarviscrawlercore.MountainStealsHistory>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jarviscrawlercore.MountainStealsHistory, 17));
};


/**
 * @param {!Array<!proto.jarviscrawlercore.MountainStealsHistory>} value
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
*/
proto.jarviscrawlercore.MountainStealsProduct.prototype.setLsthistoryList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 17, value);
};


/**
 * @param {!proto.jarviscrawlercore.MountainStealsHistory=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jarviscrawlercore.MountainStealsHistory}
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.addLsthistory = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 17, opt_value, proto.jarviscrawlercore.MountainStealsHistory, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jarviscrawlercore.MountainStealsProduct} returns this
 */
proto.jarviscrawlercore.MountainStealsProduct.prototype.clearLsthistoryList = function() {
  return this.setLsthistoryList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.RequestMountainSteals.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.RequestMountainSteals.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.RequestMountainSteals} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.RequestMountainSteals.toObject = function(includeInstance, msg) {
  var f, obj = {
    mode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    url: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.RequestMountainSteals}
 */
proto.jarviscrawlercore.RequestMountainSteals.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.RequestMountainSteals;
  return proto.jarviscrawlercore.RequestMountainSteals.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.RequestMountainSteals} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.RequestMountainSteals}
 */
proto.jarviscrawlercore.RequestMountainSteals.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.jarviscrawlercore.MountainStealsMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.RequestMountainSteals.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.RequestMountainSteals.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.RequestMountainSteals} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.RequestMountainSteals.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional MountainStealsMode mode = 1;
 * @return {!proto.jarviscrawlercore.MountainStealsMode}
 */
proto.jarviscrawlercore.RequestMountainSteals.prototype.getMode = function() {
  return /** @type {!proto.jarviscrawlercore.MountainStealsMode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.jarviscrawlercore.MountainStealsMode} value
 * @return {!proto.jarviscrawlercore.RequestMountainSteals} returns this
 */
proto.jarviscrawlercore.RequestMountainSteals.prototype.setMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string url = 2;
 * @return {string}
 */
proto.jarviscrawlercore.RequestMountainSteals.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jarviscrawlercore.RequestMountainSteals} returns this
 */
proto.jarviscrawlercore.RequestMountainSteals.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.jarviscrawlercore.ReplyMountainSteals.oneofGroups_ = [[100,101]];

/**
 * @enum {number}
 */
proto.jarviscrawlercore.ReplyMountainSteals.ReplyCase = {
  REPLY_NOT_SET: 0,
  SALE: 100,
  PRODUCT: 101
};

/**
 * @return {proto.jarviscrawlercore.ReplyMountainSteals.ReplyCase}
 */
proto.jarviscrawlercore.ReplyMountainSteals.prototype.getReplyCase = function() {
  return /** @type {proto.jarviscrawlercore.ReplyMountainSteals.ReplyCase} */(jspb.Message.computeOneofCase(this, proto.jarviscrawlercore.ReplyMountainSteals.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jarviscrawlercore.ReplyMountainSteals.prototype.toObject = function(opt_includeInstance) {
  return proto.jarviscrawlercore.ReplyMountainSteals.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jarviscrawlercore.ReplyMountainSteals} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ReplyMountainSteals.toObject = function(includeInstance, msg) {
  var f, obj = {
    mode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    sale: (f = msg.getSale()) && proto.jarviscrawlercore.MountainStealsSale.toObject(includeInstance, f),
    product: (f = msg.getProduct()) && proto.jarviscrawlercore.MountainStealsProduct.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jarviscrawlercore.ReplyMountainSteals}
 */
proto.jarviscrawlercore.ReplyMountainSteals.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jarviscrawlercore.ReplyMountainSteals;
  return proto.jarviscrawlercore.ReplyMountainSteals.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jarviscrawlercore.ReplyMountainSteals} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jarviscrawlercore.ReplyMountainSteals}
 */
proto.jarviscrawlercore.ReplyMountainSteals.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.jarviscrawlercore.MountainStealsMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    case 100:
      var value = new proto.jarviscrawlercore.MountainStealsSale;
      reader.readMessage(value,proto.jarviscrawlercore.MountainStealsSale.deserializeBinaryFromReader);
      msg.setSale(value);
      break;
    case 101:
      var value = new proto.jarviscrawlercore.MountainStealsProduct;
      reader.readMessage(value,proto.jarviscrawlercore.MountainStealsProduct.deserializeBinaryFromReader);
      msg.setProduct(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jarviscrawlercore.ReplyMountainSteals.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jarviscrawlercore.ReplyMountainSteals.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jarviscrawlercore.ReplyMountainSteals} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jarviscrawlercore.ReplyMountainSteals.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getSale();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.jarviscrawlercore.MountainStealsSale.serializeBinaryToWriter
    );
  }
  f = message.getProduct();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      proto.jarviscrawlercore.MountainStealsProduct.serializeBinaryToWriter
    );
  }
};


/**
 * optional MountainStealsMode mode = 1;
 * @return {!proto.jarviscrawlercore.MountainStealsMode}
 */
proto.jarviscrawlercore.ReplyMountainSteals.prototype.getMode = function() {
  return /** @type {!proto.jarviscrawlercore.MountainStealsMode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.jarviscrawlercore.MountainStealsMode} value
 * @return {!proto.jarviscrawlercore.ReplyMountainSteals} returns this
 */
proto.jarviscrawlercore.ReplyMountainSteals.prototype.setMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional MountainStealsSale sale = 100;
 * @return {?proto.jarviscrawlercore.MountainStealsSale}
 */
proto.jarviscrawlercore.ReplyMountainSteals.prototype.getSale = function() {
  return /** @type{?proto.jarviscrawlercore.MountainStealsSale} */ (
    jspb.Message.getWrapperField(this, proto.jarviscrawlercore.MountainStealsSale, 100));
};


/**
 * @param {?proto.jarviscrawlercore.MountainStealsSale|undefined} value
 * @return {!proto.jarviscrawlercore.ReplyMountainSteals} returns this
*/
proto.jarviscrawlercore.ReplyMountainSteals.prototype.setSale = function(value) {
  return jspb.Message.setOneofWrapperField(this, 100, proto.jarviscrawlercore.ReplyMountainSteals.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jarviscrawlercore.ReplyMountainSteals} returns this
 */
proto.jarviscrawlercore.ReplyMountainSteals.prototype.clearSale = function() {
  return this.setSale(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jarviscrawlercore.ReplyMountainSteals.prototype.hasSale = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional MountainStealsProduct product = 101;
 * @return {?proto.jarviscrawlercore.MountainStealsProduct}
 */
proto.jarviscrawlercore.ReplyMountainSteals.prototype.getProduct = function() {
  return /** @type{?proto.jarviscrawlercore.MountainStealsProduct} */ (
    jspb.Message.getWrapperField(this, proto.jarviscrawlercore.MountainStealsProduct, 101));
};


/**
 * @param {?proto.jarviscrawlercore.MountainStealsProduct|undefined} value
 * @return {!proto.jarviscrawlercore.ReplyMountainSteals} returns this
*/
proto.jarviscrawlercore.ReplyMountainSteals.prototype.setProduct = function(value) {
  return jspb.Message.setOneofWrapperField(this, 101, proto.jarviscrawlercore.ReplyMountainSteals.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jarviscrawlercore.ReplyMountainSteals} returns this
 */
proto.jarviscrawlercore.ReplyMountainSteals.prototype.clearProduct = function() {
  return this.setProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jarviscrawlercore.ReplyMountainSteals.prototype.hasProduct = function() {
  return jspb.Message.getField(this, 101) != null;
};


/**
 * @enum {number}
 */
proto.jarviscrawlercore.MountainStealsMode = {
  MSM_SALE: 0,
  MSM_PRODUCT: 1
};

goog.object.extend(exports, proto.jarviscrawlercore);
